### ISSUE TITLE
error during running the reinforcement learning 

### ISSUE THREAD

**Issue by VirtualChemist** [songleee/LS-MolGen#1]
HI,

Today I got the opportunity to use the LS-MolGen code.
During the running the reinforcement learning code, I got the error attached here, and the code ends with following error.

(LS-MolGen) users@users:~/Downloads/LS-MolGen$ python reinforcement_learning.py > rl.log
Traceback (most recent call last):
  File "/home/users/Downloads/LS-MolGen/reinforcement_learning.py", line 164, in <module>
    train_agent(restore_prior_from='data/EGFR/Transfer.ckpt',
  File "/home/users/Downloads/LS-MolGen/reinforcement_learning.py", line 125, in train_agent
    prior_likelihood[i],
IndexError: index 6 is out of bounds for dimension 0 with size 6

What is the issue?
I have installed all the packages as mentioned in environment.yml file.

Thanks,
[rl.log](https://github.com/songleee/LS-MolGen/files/11242130/rl.log)

**Comment by songleee** [comment]
The key component of reinforcement learning is the docking score, which is obtained from LeDock program. Thus, if you want to run reinforcement_learning.py script, you need firstly ensure to have installed the software of [LeDock](http://www.lephar.com/download.htm) and the tools for ligand preparing, such as [Obabel](https://github.com/openbabel/openbabel/releases). Then add the environment variables of them (refer to the way I writed in the run.pbs and change the path way to your own).

**Comment by VirtualChemist** [comment]
Thanks for you message.
The Openbabel installations solved my problem.

Thanks,
